// Travelog extended UI translations: Mandarin Chinese, Thai, Vietnamese, French, Spanish.
(() => {
  const pack = {};
  const add = (key, zh, th, vi, fr, es) => { pack[key] = { zh, th, vi, fr, es }; };

  add('pts', '积分', 'แต้ม', 'điểm', 'pts', 'pts');
  add('nav_home', '首页', 'หน้าหลัก', 'Trang chủ', 'Accueil', 'Inicio');
  add('home_welcome', '欢迎！', 'ยินดีต้อนรับ!', 'Chào mừng!', 'Bienvenue !', '¡Bienvenido!');
  add('home_coin_balance', '旅行币余额', 'ยอดเหรียญท่องเที่ยว', 'Số dư Travel Coin', 'Solde de Travel Coins', 'Saldo de Travel Coins');
  add('home_charge_ad', '看广告充值（+50）', 'ดูโฆษณา (+50)', 'Xem quảng cáo (+50)', 'Recharge pub (+50)', 'Recarga con anuncio (+50)');
  add('home_charge_pay', '付费充值', 'เติมเงิน', 'Nạp trả phí', 'Recharge payante', 'Recarga de pago');
  add('coin_charge_badge', '旅行币', 'เหรียญท่องเที่ยว', 'Travel Coin', 'Travel Coin', 'Travel Coin');
  add('coin_charge_title', '充值旅行币', 'เติมเหรียญ', 'Nạp xu', 'Recharger des coins', 'Recargar monedas');
  add('coin_charge_desc', '请选择充值方式。', 'เลือกวิธีเติมเหรียญ', 'Chọn cách nạp xu.', 'Choisissez un mode de recharge.', 'Elige un método de recarga.');
  add('coin_charge_ad_hint', '观看广告获得旅行币', 'ดูโฆษณาเพื่อรับเหรียญ', 'Xem quảng cáo để nhận xu', 'Regardez une pub et gagnez des coins', 'Mira un anuncio y gana monedas');
  add('coin_charge_pay_hint', '按需购买旅行币', 'ซื้อเหรียญตามจำนวนที่ต้องการ', 'Mua số xu bạn cần', 'Achetez la quantité nécessaire', 'Compra las monedas que necesites');
  add('home_widget_title', '我的导游收藏', 'คลังไกด์ของฉัน', 'Kho hướng dẫn của tôi', 'Mes guides', 'Mis guías');
  add('home_widget_edit', '编辑组件', 'แก้ไขวิดเจ็ต', 'Sửa tiện ích', 'Modifier les widgets', 'Editar widgets');
  add('home_widget_desc', '这里只显示已购买的导游。可添加或移除导游组件。', 'แสดงเฉพาะไกด์ที่ซื้อแล้ว เพิ่มหรือลบวิดเจ็ตได้', 'Chỉ hiển thị hướng dẫn đã mua. Thêm hoặc xóa tiện ích.', 'Seuls les guides achetés sont affichés. Ajoutez ou retirez des widgets.', 'Solo se muestran las guías compradas. Añade o quita widgets.');
  add('home_rec_title', '推荐导游', 'ไกด์แนะนำ', 'Hướng dẫn đề xuất', 'Guides recommandés', 'Guías recomendadas');
  add('home_today_title', '今日游记', 'บันทึกวันนี้', 'Nhật ký hôm nay', 'Carnets du jour', 'Diarios de hoy');
  add('home_today_info', '采用30天轮换规则', 'ใช้กฎหมุนเวียน 30 วัน', 'Áp dụng quy tắc luân phiên 30 ngày', 'Rotation sur 30 jours', 'Rotación de 30 días');
  add('home_star_title', '明星导游', 'ไกด์ดาวเด่น', 'Hướng dẫn nổi bật', 'Guides vedettes', 'Guías estrella');
  add('home_event_title', '活动与任务导游', 'ไกด์กิจกรรมและภารกิจ', 'Hướng dẫn sự kiện & nhiệm vụ', 'Guides événements et quêtes', 'Guías de eventos y misiones');
  add('ad_promo_1', '济州航空早鸟票开售！额外九折 ✈️', 'ตั๋ว Early Bird ของ Jeju Air เปิดแล้ว! ลดเพิ่ม 10% ✈️', 'Vé sớm Jeju Air đã mở! Giảm thêm 10% ✈️', 'Billets Early Bird Jeju Air : -10 % en plus ✈️', '¡Billetes anticipados de Jeju Air! 10 % extra ✈️');
  add('ad_promo_2', '订阅Travelog Pass，畅享无限语音导游 👑', 'Travelog Pass: ฟังไกด์เสียงไม่จำกัด 👑', 'Travelog Pass: hướng dẫn âm thanh không giới hạn 👑', 'Travelog Pass : guides audio illimités 👑', 'Travelog Pass: audioguías ilimitadas 👑');
  add('ad_promo_3', '完成水原华城任务，领取便利店礼券 🎁', 'ทำภารกิจป้อมฮวาซองสำเร็จ รับคูปองร้านสะดวกซื้อ 🎁', 'Hoàn thành nhiệm vụ pháo đài Hwaseong để nhận phiếu quà tặng 🎁', 'Terminez la quête de Hwaseong et gagnez un bon cadeau 🎁', 'Completa la misión de Hwaseong y gana un cupón 🎁');
  add('msg_badge', '消息', 'ข้อความ', 'Tin nhắn', 'Messages', 'Mensajes');
  add('msg_title', '消息箱', 'กล่องข้อความ', 'Hộp tin nhắn', 'Messagerie', 'Buzón');
  add('msg_desc', '分别查看收到和已发送的消息。', 'ดูข้อความที่ได้รับและส่งแล้วแยกกัน', 'Xem riêng tin đã nhận và đã gửi.', 'Consultez séparément les messages reçus et envoyés.', 'Consulta por separado los mensajes recibidos y enviados.');
  add('confirm', '确认', 'ยืนยัน', 'Xác nhận', 'Confirmer', 'Confirmar');
  add('ad_sim_title', '正在播放赞助广告', 'กำลังเล่นโฆษณาสปอนเซอร์', 'Đang phát quảng cáo tài trợ', 'Publicité sponsorisée', 'Reproduciendo anuncio patrocinado');
  add('ad_sim_desc', '完整观看广告可获得50旅行币。', 'ดูโฆษณาจบเพื่อรับ 50 เหรียญ', 'Xem hết quảng cáo để nhận 50 xu.', 'Regardez la publicité jusqu’au bout pour gagner 50 coins.', 'Mira el anuncio completo para ganar 50 monedas.');
  add('ad_skip', '关闭', 'ปิด', 'Đóng', 'Fermer', 'Cerrar');
  add('pay_badge', '旅行币商店', 'ร้านเหรียญ', 'Cửa hàng xu', 'Boutique de coins', 'Tienda de monedas');
  add('pay_title', '购买旅行币', 'ซื้อเหรียญท่องเที่ยว', 'Mua Travel Coin', 'Acheter des Travel Coins', 'Comprar Travel Coins');
  add('pay_desc', '用于购买优质本地语音导游。', 'ใช้ซื้อไกด์เสียงท้องถิ่นพรีเมียม', 'Dùng để mua hướng dẫn âm thanh cao cấp.', 'Utilisez-les pour acheter des guides audio premium.', 'Úsalas para comprar audioguías prémium.');
  add('widget_badge', '首页组件', 'วิดเจ็ตหน้าหลัก', 'Tiện ích trang chủ', 'Widgets d’accueil', 'Widgets de inicio');
  add('widget_config_title', '编辑收藏组件', 'แก้ไขวิดเจ็ตคลังไกด์', 'Sửa tiện ích kho hướng dẫn', 'Modifier les widgets', 'Editar widgets');
  add('widget_config_desc', '选择要在首页显示的已购导游。', 'เลือกไกด์ที่ซื้อแล้วเพื่อแสดงบนหน้าหลัก', 'Chọn hướng dẫn đã mua để hiển thị trên trang chủ.', 'Choisissez les guides achetés à afficher sur l’accueil.', 'Elige las guías compradas que se mostrarán en Inicio.');
  add('widget_limit_hint', '建议最多显示4个', 'แนะนำไม่เกิน 4 รายการ', 'Khuyến nghị tối đa 4', '4 maximum recommandé', 'Máximo recomendado: 4');
  add('active_guide_title', '当前导游', 'ไกด์ปัจจุบัน', 'Hướng dẫn hiện tại', 'Guide actif', 'Guía activa');
  add('intro_video', '介绍视频', 'วิดีโอแนะนำ', 'Video giới thiệu', 'Vidéo d’introduction', 'Video de introducción');
  add('greeting', '收听问候', 'ฟังคำทักทาย', 'Nghe lời chào', 'Écouter le message', 'Escuchar saludo');
  add('route_guide_list', '游览地点', 'รายการสถานที่', 'Danh sách điểm đến', 'Étapes du circuit', 'Lugares del recorrido');
  add('walking', '移动中…', 'กำลังเดินทาง...', 'Đang di chuyển...', 'En déplacement…', 'En movimiento...');
  add('audio_guide', '语音导览已启动', 'เริ่มไกด์เสียงแล้ว', 'Đã bật hướng dẫn âm thanh', 'Guide audio déclenché', 'Audioguía activada');
  add('vlog_playing', '正在播放Vlog视频…', 'กำลังเล่นวิดีโอ Vlog...', 'Đang phát video Vlog...', 'Lecture du vlog…', 'Reproduciendo vlog...');
  add('blog_feed_title', '旅行日志与故事', 'บันทึกและเรื่องราวการเดินทาง', 'Nhật ký & câu chuyện du lịch', 'Carnets et récits de voyage', 'Diarios e historias de viaje');
  add('filter_all', '全部', 'ทั้งหมด', 'Tất cả', 'Tout', 'Todo');
  add('filter_korea', '韩国', 'เกาหลีใต้', 'Hàn Quốc', 'Corée du Sud', 'Corea del Sur');
  add('filter_japan', '日本', 'ญี่ปุ่น', 'Nhật Bản', 'Japon', 'Japón');
  add('filter_europe', '欧洲', 'ยุโรป', 'Châu Âu', 'Europe', 'Europa');
  add('scratch_title', '刮刮乐优惠券', 'คูปองขูด', 'Phiếu cào giảm giá', 'Coupon à gratter', 'Cupón para rascar');
  add('scratch_desc', '刮开银色区域，赢取旅行折扣券！', 'ขูดพื้นผิวสีเงินเพื่อรับคูปองส่วนลด!', 'Cào lớp bạc để nhận phiếu giảm giá du lịch!', 'Grattez la zone argentée pour gagner une réduction !', '¡Rasca la zona plateada para conseguir un descuento!');
  add('scratch_reset', '再刮一次（消耗50积分）', 'ลองบัตรใหม่ (ใช้ 50 แต้ม)', 'Thử thẻ mới (tốn 50 điểm)', 'Nouvelle carte (50 pts)', 'Nueva tarjeta (50 pts)');
  add('spin_title', '每日旅行转盘', 'วงล้อท่องเที่ยวรายวัน', 'Vòng quay du lịch hằng ngày', 'Roue quotidienne', 'Ruleta diaria de viaje');
  add('spin_desc', '转动转盘，赢取优惠券、积分或礼物！', 'หมุนวงล้อเพื่อลุ้นคูปอง แต้ม หรือของขวัญ!', 'Quay để nhận phiếu giảm giá, điểm hoặc quà!', 'Tournez la roue pour gagner coupons, points ou cadeaux !', '¡Gira la ruleta para ganar cupones, puntos o regalos!');
  add('events_calendar_title', '全球旅行活动与任务', 'กิจกรรมและภารกิจท่องเที่ยวทั่วโลก', 'Sự kiện & nhiệm vụ du lịch toàn cầu', 'Événements et quêtes du monde', 'Eventos y misiones globales');
  add('my_coupons_title', '我的优惠券', 'กระเป๋าคูปองของฉัน', 'Ví phiếu giảm giá', 'Mon portefeuille de coupons', 'Mi cartera de cupones');
  add('gdrive_storage_title', 'Google云端硬盘存储', 'พื้นที่เก็บข้อมูล Google Drive', 'Bộ nhớ Google Drive', 'Stockage Google Drive', 'Almacenamiento de Google Drive');
  add('gdrive_storage_desc', '将录制的导游、脚本和视频上传到Google云端硬盘文件夹。', 'อัปโหลดเสียง สคริปต์ และวิดีโอไปยังโฟลเดอร์ Google Drive', 'Tải hướng dẫn, kịch bản và video lên thư mục Google Drive.', 'Importez guides, scripts et vidéos dans votre dossier Google Drive.', 'Sube guías, guiones y videos a tu carpeta de Google Drive.');
  add('gdrive_owner', '存储空间所有者', 'เจ้าของพื้นที่', 'Chủ sở hữu', 'Propriétaire', 'Propietario');
  add('gdrive_dest', '目标文件夹', 'โฟลเดอร์ปลายทาง', 'Thư mục đích', 'Dossier cible', 'Carpeta de destino');
  add('gdrive_open_btn', '打开云端硬盘文件夹', 'เปิดโฟลเดอร์ Drive', 'Mở thư mục Drive', 'Ouvrir le dossier Drive', 'Abrir carpeta de Drive');
  add('gdrive_download_data_label', '下载创作数据', 'ดาวน์โหลดข้อมูลงานสร้าง', 'Tải dữ liệu sáng tạo', 'Télécharger les données', 'Descargar datos de creación');
  add('gdrive_download_json', '下载导游数据（.json）', 'ดาวน์โหลดข้อมูลไกด์ (.json)', 'Tải dữ liệu hướng dẫn (.json)', 'Télécharger les données (.json)', 'Descargar datos de guía (.json)');
  add('builder_title', '地图导游制作器', 'เครื่องมือสร้างไกด์แผนที่', 'Trình tạo hướng dẫn bản đồ', 'Créateur de guide cartographique', 'Creador de guías de mapa');
  add('builder_desc', '创建专属导游！在地图上添加坐标，再上传音频或编写说明。', 'สร้างไกด์ของคุณ เพิ่มพิกัดบนแผนที่แล้วอัปโหลดเสียงหรือเขียนคำแนะนำ', 'Tạo hướng dẫn riêng! Đặt điểm trên bản đồ rồi tải âm thanh hoặc viết nội dung.', 'Créez votre guide : placez des points puis ajoutez audio ou textes.', 'Crea tu guía: marca puntos y añade audio o textos.');
  add('builder_tour_name', '导游名称', 'ชื่อไกด์ทัวร์', 'Tên hướng dẫn', 'Nom du guide', 'Nombre de la guía');
  add('builder_select_coords', '已选地图标记', 'หมุดแผนที่ที่เลือก', 'Ghim bản đồ đã chọn', 'Repères sélectionnés', 'Pines seleccionados');
  add('no_pins_placeholder', '请到地图页面添加标记！', 'ไปที่หน้าแผนที่เพื่อเพิ่มหมุด!', 'Hãy sang tab Bản đồ để đặt ghim!', 'Allez sur la carte pour placer des repères !', '¡Ve al mapa para colocar pines!');
  add('save_tour', '发布导游', 'เผยแพร่ไกด์', 'Xuất bản hướng dẫn', 'Publier le guide', 'Publicar guía');
  add('clear_pins', '重置标记', 'รีเซ็ตหมุด', 'Đặt lại ghim', 'Réinitialiser les repères', 'Restablecer pines');
  add('recorder_title', '互动语音录制室', 'สตูดิโอบันทึกเสียงไกด์', 'Phòng thu hướng dẫn tương tác', 'Studio d’enregistrement du guide', 'Estudio de grabación de guía');
  add('recorder_desc', '录制到达标记地点时播放的详细说明。', 'บันทึกคำแนะนำที่จะเล่นเมื่อถึงหมุด', 'Ghi âm nội dung phát khi đến vị trí ghim.', 'Enregistrez les instructions jouées à l’arrivée sur un repère.', 'Graba las indicaciones que se reproducirán al llegar a un punto.');
  add('recorder_ready', '点击麦克风开始录音', 'กดไมโครโฟนเพื่อเริ่มบันทึก', 'Nhấn mic để bắt đầu ghi', 'Cliquez sur le micro pour enregistrer', 'Pulsa el micrófono para grabar');
  add('script_start', '“出发吧！”', '“ออกเดินทางกัน!”', '“Bắt đầu thôi!”', '« C’est parti ! »', '“¡Empezamos!”');
  add('script_turn', '“请在这里左转…”', '“เลี้ยวซ้ายตรงนี้...”', '“Rẽ trái tại đây...”', '« Tournez à gauche ici… »', '“Gira a la izquierda aquí...”');
  add('script_eat', '“这里有特别优惠！”', '“รับส่วนลดพิเศษที่นี่!”', '“Nhận ưu đãi đặc biệt tại đây!”', '« Profitez d’une remise ici ! »', '“¡Consigue un descuento aquí!”');
  add('script_morning', '“早上好！”', '“สวัสดีตอนเช้า!”', '“Chào buổi sáng!”', '« Bonjour ! »', '“¡Buenos días!”');
  add('market_title', '语音样本市场', 'ตลาดตัวอย่างเสียง', 'Chợ mẫu giọng nói', 'Marché des voix', 'Mercado de voces');
  add('market_desc', '不想亲自录音？购买高品质合成语音包自动朗读脚本。', 'ไม่สะดวกอัดเสียง? ซื้อแพ็กเสียงสังเคราะห์เพื่ออ่านข้อความอัตโนมัติ', 'Không muốn tự thu? Mua gói giọng tổng hợp để đọc kịch bản.', 'Pas envie d’enregistrer ? Achetez une voix de synthèse.', '¿No quieres grabarte? Compra un paquete de voz sintética.');
  add('media_storage_title', 'GitHub媒体存储', 'พื้นที่เก็บสื่อ GitHub', 'Kho phương tiện GitHub', 'Stockage média GitHub', 'Almacenamiento multimedia de GitHub');
  add('media_storage_desc', '将生成的音频和视频以可播放的压缩文件保存到Travelog GitHub仓库。', 'บันทึกเสียงและวิดีโอเป็นไฟล์บีบอัดที่เล่นได้ใน GitHub', 'Lưu âm thanh/video dưới dạng tệp nén có thể phát trong GitHub.', 'Enregistrez audio et vidéo compressés dans le dépôt GitHub.', 'Guarda audio y video comprimidos en el repositorio de GitHub.');
  add('media_storage_repo', '仓库', 'ที่เก็บ', 'Kho mã', 'Dépôt', 'Repositorio');
  add('media_storage_audio_path', '音频路径', 'พาธเสียง', 'Đường dẫn âm thanh', 'Chemin audio', 'Ruta de audio');
  add('media_storage_video_path', '视频路径', 'พาธวิดีโอ', 'Đường dẫn video', 'Chemin vidéo', 'Ruta de video');
  add('media_storage_token_status', '令牌状态', 'สถานะโทเค็น', 'Trạng thái token', 'État du jeton', 'Estado del token');
  add('media_storage_token_label', '测试上传用GitHub令牌', 'โทเค็น GitHub สำหรับทดสอบอัปโหลด', 'Token GitHub để tải thử', 'Jeton GitHub pour le test', 'Token de GitHub para pruebas');
  add('media_storage_warning', '仅用于原型测试。请勿将令牌提交到GitHub。', 'ใช้ทดสอบต้นแบบเท่านั้น ห้ามบันทึกโทเค็นลง GitHub', 'Chỉ để thử nghiệm. Không đưa token lên GitHub.', 'Réservé au prototype. Ne publiez jamais le jeton sur GitHub.', 'Solo para pruebas. No guardes el token en GitHub.');
  add('media_storage_save_token', '保存令牌', 'บันทึกโทเค็น', 'Lưu token', 'Enregistrer le jeton', 'Guardar token');
  add('media_storage_clear_token', '清除', 'ล้าง', 'Xóa', 'Effacer', 'Borrar');
  add('media_storage_test', '连接测试', 'ทดสอบการเชื่อมต่อ', 'Kiểm tra kết nối', 'Tester', 'Probar conexión');
  add('media_storage_audio_file', '音频文件测试', 'ทดสอบไฟล์เสียง', 'Thử tệp âm thanh', 'Test du fichier audio', 'Prueba de archivo de audio');
  add('media_storage_video_file', '视频文件测试', 'ทดสอบไฟล์วิดีโอ', 'Thử tệp video', 'Test du fichier vidéo', 'Prueba de archivo de video');
  add('media_storage_upload_audio', '上传音频源文件', 'อัปโหลดไฟล์เสียง', 'Tải nguồn âm thanh', 'Importer la source audio', 'Subir archivo de audio');
  add('media_storage_upload_video', '上传视频源文件', 'อัปโหลดไฟล์วิดีโอ', 'Tải nguồn video', 'Importer la source vidéo', 'Subir archivo de video');
  add('quest_active', '进行中的任务', 'ภารกิจที่กำลังทำ', 'Nhiệm vụ đang hoạt động', 'Quête active', 'Misión activa');
  add('quest_steps_title', '任务进度', 'ขั้นตอนภารกิจ', 'Các bước nhiệm vụ', 'Étapes de la quête', 'Etapas de la misión');
  add('radar_title', 'GPS接近雷达', 'เรดาร์ระยะใกล้ GPS', 'Radar khoảng cách GPS', 'Radar de proximité GPS', 'Radar de proximidad GPS');
  add('radar_desc', '在地图上模拟移动并接近坐标线索。进入10米内即可解锁！', 'จำลองการเดินบนแผนที่ เข้าใกล้เบาะแสภายใน 10 ม. เพื่อปลดล็อก!', 'Mô phỏng di chuyển; đến trong 10 m để mở khóa manh mối!', 'Simulez la marche et approchez-vous à moins de 10 m pour déverrouiller l’indice !', 'Simula el recorrido y acércate a menos de 10 m para desbloquear la pista.');
  add('clue_unlocked_title', '已到达线索地点！', 'ถึงตำแหน่งเบาะแสแล้ว!', 'Đã đến vị trí manh mối!', 'Lieu de l’indice atteint !', '¡Ubicación de la pista alcanzada!');
  add('solve', '提交答案', 'ตรวจคำตอบ', 'Giải', 'Résoudre', 'Resolver');
  add('radar_clue_hint', '前往地图上的粉色任务标记以触发线索。', 'ไปยังหมุดภารกิจสีชมพูบนแผนที่เพื่อรับเบาะแส', 'Đi đến biểu tượng nhiệm vụ màu hồng để kích hoạt manh mối.', 'Rejoignez le repère rose sur la carte pour activer l’indice.', 'Ve al marcador rosa del mapa para activar la pista.');
  add('teleport_btn', '直接前往线索GPS地点', 'ไปยังจุด GPS ของเบาะแสทันที', 'Đi ngay đến vị trí GPS của manh mối', 'Aller au point GPS de l’indice', 'Ir al punto GPS de la pista');
  add('onboarding_step_login', '第1/2步 · 登录', 'ขั้นตอน 1/2 · เข้าสู่ระบบ', 'Bước 1/2 · Đăng nhập', 'Étape 1/2 · Connexion', 'Paso 1/2 · Iniciar sesión');
  add('onboarding_step_profile', '第2/2步 · 个人资料', 'ขั้นตอน 2/2 · โปรไฟล์', 'Bước 2/2 · Hồ sơ', 'Étape 2/2 · Profil', 'Paso 2/2 · Perfil');
  add('onboarding_title', '欢迎使用Travelog', 'ยินดีต้อนรับสู่ Travelog', 'Chào mừng đến với Travelog', 'Bienvenue sur Travelog', 'Te damos la bienvenida a Travelog');
  add('onboarding_subtitle', '跟随本地导游，解锁地图故事并收集旅行奖励。', 'ติดตามไกด์ท้องถิ่น ปลดล็อกเรื่องราวบนแผนที่ และรับรางวัล', 'Theo hướng dẫn địa phương, mở khóa câu chuyện và nhận thưởng.', 'Suivez des guides locaux, découvrez des récits et gagnez des récompenses.', 'Sigue a guías locales, descubre historias y gana recompensas.');
  add('login_google', '使用Google继续', 'ดำเนินการต่อด้วย Google', 'Tiếp tục với Google', 'Continuer avec Google', 'Continuar con Google');
  add('login_naver', '使用Naver继续', 'ดำเนินการต่อด้วย Naver', 'Tiếp tục với Naver', 'Continuer avec Naver', 'Continuar con Naver');
  add('login_email', '使用邮箱继续', 'ดำเนินการต่อด้วยอีเมล', 'Tiếp tục với email', 'Continuer avec un e-mail', 'Continuar con correo');
  add('login_guest', '以访客身份体验', 'ทดลองในฐานะแขก', 'Dùng thử với tư cách khách', 'Essayer en tant qu’invité', 'Probar como invitado');
  add('onboarding_privacy_hint', '此原型不会发送登录信息，只会进入下一设置步骤。', 'ต้นแบบนี้ไม่ส่งข้อมูลเข้าสู่ระบบ เพียงไปยังขั้นตอนถัดไป', 'Bản mẫu không gửi dữ liệu đăng nhập, chỉ chuyển sang bước tiếp theo.', 'Ce prototype n’envoie aucune donnée de connexion.', 'Este prototipo no envía datos de inicio de sesión.');
  add('onboarding_feature_guide', 'GPS语音导游', 'ไกด์เสียง GPS', 'Hướng dẫn âm thanh GPS', 'Guide audio GPS', 'Audioguía GPS');
  add('onboarding_feature_reward', '优惠券与任务', 'คูปองและภารกิจ', 'Phiếu giảm giá & nhiệm vụ', 'Coupons et quêtes', 'Cupones y misiones');
  add('onboarding_feature_creator', '导游制作工作室', 'สตูดิโอสร้างไกด์', 'Studio tạo hướng dẫn', 'Studio de création', 'Estudio de creación');
  add('onboarding_profile_title', '设置个人资料', 'ตั้งค่าโปรไฟล์', 'Thiết lập hồ sơ', 'Configurez votre profil', 'Configura tu perfil');
  add('onboarding_profile_subtitle', '开始探索前，请选择昵称和头像。', 'เลือกชื่อเล่นและรูปประจำตัวก่อนเริ่มสำรวจ', 'Chọn biệt danh và ảnh đại diện trước khi khám phá.', 'Choisissez un pseudo et un avatar avant de commencer.', 'Elige un apodo y un avatar antes de explorar.');
  add('avatar_hint', '选择预设头像或上传照片', 'เลือกภาพที่มีหรืออัปโหลดรูป', 'Chọn ảnh có sẵn hoặc tải ảnh riêng', 'Choisissez un avatar ou importez une photo', 'Elige un avatar o sube una foto');
  add('nickname_label', '创建昵称', 'สร้างชื่อเล่น', 'Tạo biệt danh', 'Créer un pseudo', 'Crear apodo');
  add('nickname_placeholder', '例如：旅行者', 'เช่น นักเดินทาง', 'ví dụ: lữ khách', 'ex. voyageur', 'p. ej., viajero');
  add('nickname_check', '检查', 'ตรวจสอบ', 'Kiểm tra', 'Vérifier', 'Verificar');
  add('start_exploring', '开始探索！', 'เริ่มสำรวจ!', 'Bắt đầu khám phá!', 'Commencer !', '¡Empezar a explorar!');
  add('back_to_login', '返回', 'ย้อนกลับ', 'Quay lại', 'Retour', 'Volver');
  add('profile_manage_badge', '个人资料管理', 'จัดการโปรไฟล์', 'Quản lý hồ sơ', 'Gestion du profil', 'Gestión del perfil');
  add('profile_manage_title', '管理我的个人资料', 'จัดการโปรไฟล์ของฉัน', 'Quản lý hồ sơ của tôi', 'Gérer mon profil', 'Gestionar mi perfil');
  add('profile_manage_desc', '可随时更改昵称、照片、上传图片或示例头像。', 'เปลี่ยนชื่อเล่น รูปภาพ หรืออวตารได้ทุกเมื่อ', 'Đổi biệt danh, ảnh hoặc avatar bất cứ lúc nào.', 'Modifiez votre pseudo, photo ou avatar à tout moment.', 'Cambia tu apodo, foto o avatar cuando quieras.');
  add('profile_use_my_photo', '选择我的照片/图片', 'เลือกรูปภาพของฉัน', 'Chọn ảnh của tôi', 'Choisir ma photo', 'Elegir mi foto');
  add('profile_image_note', '此原型中的图片仅保存在当前浏览器。', 'รูปจะถูกบันทึกเฉพาะในเบราว์เซอร์นี้', 'Ảnh chỉ được lưu trong trình duyệt này.', 'L’image est enregistrée uniquement dans ce navigateur.', 'La imagen solo se guarda en este navegador.');
  add('profile_nickname_label', '昵称', 'ชื่อเล่น', 'Biệt danh', 'Pseudo', 'Apodo');
  add('profile_temp_image_title', '选择示例头像', 'เลือกอวตารตัวอย่าง', 'Chọn avatar mẫu', 'Choisir un avatar', 'Elegir avatar');
  add('profile_emoji_title', '选择简易图标', 'เลือกไอคอนแบบง่าย', 'Chọn biểu tượng đơn giản', 'Choisir une icône', 'Elegir icono');
  add('profile_reset_onboarding', '重新开始设置', 'เริ่มการตั้งค่าใหม่', 'Thiết lập lại', 'Recommencer la configuration', 'Reiniciar configuración');
  add('profile_cancel', '取消', 'ยกเลิก', 'Hủy', 'Annuler', 'Cancelar');
  add('profile_save', '保存', 'บันทึก', 'Lưu', 'Enregistrer', 'Guardar');
  add('profile_saved_toast', '个人资料已更新！', 'อัปเดตโปรไฟล์แล้ว!', 'Đã cập nhật hồ sơ!', 'Profil mis à jour !', '¡Perfil actualizado!');
  add('profile_open_toast', '正在打开个人资料管理…', 'กำลังเปิดการจัดการโปรไฟล์...', 'Đang mở quản lý hồ sơ...', 'Ouverture du profil…', 'Abriendo el perfil...');
  add('map_top_badge', '实时旅行地图', 'แผนที่ท่องเที่ยวสด', 'Bản đồ du lịch trực tiếp', 'Carte de voyage en direct', 'Mapa de viaje en vivo');
  add('map_route_title', '景福宫本地游', 'ทัวร์ท้องถิ่นพระราชวังคยองบก', 'Tour địa phương Gyeongbokgung', 'Visite locale de Gyeongbokgung', 'Tour local de Gyeongbokgung');
  add('map_route_desc', '在一个画面中查看GPS位置、导游点和个人备忘。', 'ดู GPS จุดไกด์ และบันทึกส่วนตัวในหน้าเดียว', 'Xem GPS, điểm hướng dẫn và ghi chú trên một màn hình.', 'Affichez GPS, points du guide et mémos sur un seul écran.', 'Consulta GPS, puntos de guía y notas en una sola pantalla.');
  add('map_stat_stops', '站点', 'จุดแวะ', 'Điểm dừng', 'Étapes', 'Paradas');
  add('map_stat_memos', '备忘', 'บันทึก', 'Ghi chú', 'Mémos', 'Notas');
  add('map_stat_gps', 'GPS', 'GPS', 'GPS', 'GPS', 'GPS');
  add('map_mini_guide', '推荐导游', 'ไกด์แนะนำ', 'Hướng dẫn đề xuất', 'Guide recommandé', 'Guía recomendada');
  add('map_control_gps', '实时GPS', 'GPS สด', 'GPS trực tiếp', 'GPS en direct', 'GPS en vivo');
  add('map_control_gps_on', '正在跟踪', 'กำลังติดตาม', 'Đang theo dõi', 'Suivi actif', 'Rastreando');
  add('map_control_memo', '备忘', 'บันทึก', 'Ghi chú', 'Mémo', 'Nota');
  add('map_control_sim', '步行测试', 'ทดสอบการเดิน', 'Thử đi bộ', 'Test de marche', 'Prueba de caminata');
  add('map_control_sim_on', '测试中', 'กำลังทดสอบ', 'Đang thử', 'Test en cours', 'Probando');
  add('map_control_recenter', '我的位置', 'ตำแหน่งของฉัน', 'Vị trí của tôi', 'Ma position', 'Mi ubicación');
  add('map_legend_current', '我', 'ฉัน', 'Tôi', 'Moi', 'Yo');
  add('map_legend_audio', '音频', 'เสียง', 'Âm thanh', 'Audio', 'Audio');
  add('map_legend_video', '视频', 'วิดีโอ', 'Video', 'Vidéo', 'Video');
  add('map_legend_coupon', '优惠券', 'คูปอง', 'Phiếu giảm giá', 'Coupon', 'Cupón');
  add('map_legend_memo', '备忘', 'บันทึก', 'Ghi chú', 'Mémo', 'Nota');
  add('map_current_status', '当前地图状态', 'สถานะแผนที่ปัจจุบัน', 'Trạng thái bản đồ', 'État actuel de la carte', 'Estado actual del mapa');
  add('map_coords_waiting', '开启GPS后将显示坐标。', 'เปิด GPS เพื่อแสดงพิกัด', 'Bật GPS để hiển thị tọa độ.', 'Activez le GPS pour afficher vos coordonnées.', 'Activa el GPS para ver tus coordenadas.');
  add('map_accuracy_waiting', '位置精度将显示在这里。', 'ความแม่นยำของตำแหน่งจะแสดงที่นี่', 'Độ chính xác vị trí sẽ hiện ở đây.', 'La précision de la position apparaîtra ici.', 'La precisión de la ubicación aparecerá aquí.');
  add('gps_waiting', '等待GPS…', 'กำลังรอ GPS...', 'Đang chờ GPS...', 'En attente du GPS…', 'Esperando GPS...');
  add('gps_locating', '正在定位…', 'กำลังค้นหาตำแหน่ง...', 'Đang tìm vị trí...', 'Recherche de votre position…', 'Buscando tu ubicación...');
  add('gps_my_location', '我的当前位置', 'ตำแหน่งปัจจุบันของฉัน', 'Vị trí hiện tại của tôi', 'Ma position actuelle', 'Mi ubicación actual');
  add('memo_modal_title', '在此位置留下备忘', 'ฝากบันทึกไว้ที่นี่', 'Để lại ghi chú tại đây', 'Laisser un mémo ici', 'Dejar una nota aquí');
  add('memo_modal_desc', '在当前GPS位置保存简短备忘。', 'บันทึกข้อความสั้นที่ตำแหน่ง GPS ปัจจุบัน', 'Lưu ghi chú ngắn tại vị trí GPS hiện tại.', 'Enregistrez une note à votre position GPS actuelle.', 'Guarda una nota en tu ubicación GPS actual.');
  add('memo_text_placeholder', '写下此地点的备忘…', 'เขียนบันทึกสำหรับสถานที่นี้...', 'Viết ghi chú cho địa điểm này...', 'Écrivez une note pour ce lieu…', 'Escribe una nota para este lugar...');
  add('memo_cancel', '取消', 'ยกเลิก', 'Hủy', 'Annuler', 'Cancelar');
  add('memo_save', '保存备忘', 'บันทึกโน้ต', 'Lưu ghi chú', 'Enregistrer le mémo', 'Guardar nota');
  add('nav_map', '地图', 'แผนที่', 'Bản đồ', 'Carte', 'Mapa');
  add('nav_location', '我的位置', 'ตำแหน่งของฉัน', 'Vị trí của tôi', 'Ma position', 'Mi ubicación');
  add('nav_explore', '动态', 'ฟีด', 'Bảng tin', 'Fil', 'Feed');
  add('nav_rewards', '优惠券与活动', 'คูปองและกิจกรรม', 'Phiếu & sự kiện', 'Coupons & événements', 'Cupones y eventos');
  add('nav_creator', '工作室', 'สตูดิโอ', 'Studio', 'Studio', 'Estudio');
  add('location_running_guide', '进行中的导游', 'ไกด์ที่กำลังใช้งาน', 'Hướng dẫn đang chạy', 'Guide en cours', 'Guía en curso');
  add('location_guide_ready', '待机', 'พร้อม', 'Sẵn sàng', 'Prêt', 'Listo');
  add('location_guide_running', '进行中', 'กำลังทำงาน', 'Đang chạy', 'En cours', 'En curso');
  add('location_guide_start', '开始', 'เริ่ม', 'Bắt đầu', 'Démarrer', 'Iniciar');
  add('location_guide_stop', '结束', 'เลิก', 'Kết thúc', 'Quitter', 'Salir');
  add('coupon_event_quest_title', '优惠券与活动任务', 'คูปอง กิจกรรม และภารกิจ', 'Phiếu, sự kiện & nhiệm vụ', 'Coupons, événements et quêtes', 'Cupones, eventos y misiones');
  add('coupon_event_quest_desc', '在同一页面查看优惠活动和位置任务。', 'ดูคูปองและภารกิจตามตำแหน่งในหน้าเดียว', 'Xem sự kiện và nhiệm vụ vị trí trên một màn hình.', 'Retrouvez événements et missions géolocalisées au même endroit.', 'Consulta eventos y misiones de ubicación en una sola pantalla.');
  add('share', '分享', 'แชร์', 'Chia sẻ', 'Partager', 'Compartir');
  add('search_placeholder', '搜索游记…', 'ค้นหาบันทึก...', 'Tìm nhật ký...', 'Rechercher des carnets…', 'Buscar diarios...');
  add('puzzle_placeholder', '输入密码或答案…', 'กรอกรหัสหรือคำตอบ...', 'Nhập mật mã hoặc đáp án...', 'Saisissez le mot de passe ou la réponse…', 'Escribe la contraseña o respuesta...');

  window.TravelogLanguagePack = pack;
})();
